version: "3"

services:
  db: 
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'myapp'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - dbData:/var/lib/mysql
  app:
    build: .
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    depends_on:
      - db
volumes:
  dbData: