version: "3"

services:
  db: 
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - '${DB_PORT}:3306'
    expose:
      - '3306'
    volumes:
      - dbData:/var/lib/mysql
  app:
    build: .
    restart: always
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - ./src:/app/src
    depends_on:
      - db
volumes:
  dbData: